// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (
    id,
    title,
    icon,
    parent_id,
    owner_id,
    sort_order,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    (
        SELECT COALESCE(MAX(sort_order), -1) + 1
        FROM collections
        WHERE owner_id = $5
    ),
    $6,
    $7
) RETURNING id, title, icon, parent_id, owner_id, sort_order, created_at, updated_at
`

type CreateCollectionParams struct {
	ID        string
	Title     string
	Icon      sql.NullString
	ParentID  sql.NullString
	OwnerID   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection,
		arg.ID,
		arg.Title,
		arg.Icon,
		arg.ParentID,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Icon,
		&i.ParentID,
		&i.OwnerID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollection = `-- name: GetCollection :one
SELECT id, title, icon, parent_id, owner_id, sort_order, created_at, updated_at
FROM collections
WHERE id = $1
  AND owner_id = $2
`

type GetCollectionParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, arg.ID, arg.OwnerID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Icon,
		&i.ParentID,
		&i.OwnerID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET
    title = $1,
    icon = $2,
    parent_id = $3,
    updated_at = $4
WHERE id = $5
  AND owner_id = $6
RETURNING id, title, icon, parent_id, owner_id, sort_order, created_at, updated_at
`

type UpdateCollectionParams struct {
	Title     string
	Icon      sql.NullString
	ParentID  sql.NullString
	UpdatedAt time.Time
	ID        string
	OwnerID   string
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, updateCollection,
		arg.Title,
		arg.Icon,
		arg.ParentID,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Icon,
		&i.ParentID,
		&i.OwnerID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
