// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Collection struct {
	ID        string
	Title     string
	Icon      sql.NullString
	ParentID  sql.NullString
	OwnerID   string
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	TokenHash []byte
	AccountID string
	ExpiresAt time.Time
	CreatedAt time.Time
}
