// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    token_hash,
    account_id,
    expires_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type CreateSessionParams struct {
	TokenHash []byte
	AccountID string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.AccountID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT
    token_hash,
    account_id,
    expires_at,
    created_at
FROM sessions
WHERE token_hash = $1
`

func (q *Queries) FindSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, findSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.AccountID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
